wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.6.9
      5: 0.10.33
      8:
      - 5
bin_size:
  desc: null
  value: 32
data_dir:
  desc: null
  value: ../i_3072_w_1
filtN_1:
  desc: null
  value: 256
filtN_2:
  desc: null
  value: 2048
l_rate:
  desc: null
  value: 0.001
loss_fn:
  desc: null
  value: poisson
model_fn:
  desc: null
  value: basenji_v2
num_epochs:
  desc: null
  value: 100
task_type:
  desc: null
  value: quant
window_size:
  desc: null
  value: 2048
